### ISSUE TITLE
convert lua number to double (currently float)

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture-Pro_firmware#101]
bits in 29 bit CAN IDs are getting truncated, and it's affecting certain ECU integrations, such as AEM.

Convert Lua number to double to provides space for 29 bit numbers (and more)

**Comment by stieg** [comment]
Not going to make 2.8.7 because MK1 is still part of the tool chain.  Will come in 2.9.0 when MK1 and MK2 are on separate release cycles.
