### ISSUE TITLE
When logging at 25hz, 10hz are drop to 5hz

### ISSUE THREAD

**Issue by kokarez** [autosportlabs/RaceCapture-Pro_firmware#1022]
When logging at 25hz, 10hz are drop to 5hz. This is due to tick count of 25hz not overlapping with the 10hz, thus half of the ticks will be drop by the should_sample which force all sample to be align on 25hz.

**Comment by brentpicasso** [comment]
Thanks for the note. Can you attach an example config that reproduces this problem?

**Comment by xavierd** [comment]
I've also just seen this. The data logged for configured 10Hz sensors is actually only logged at 5Hz, including the GPS data :(. See the attached configuration.
[conf.txt](https://github.com/autosportlabs/RaceCapture-Pro_firmware/files/3829042/conf.txt)

**Comment by xavierd** [comment]
And this is a log generated with the config: [rc_2.log](https://github.com/autosportlabs/RaceCapture-Pro_firmware/files/3829046/rc_2.log). If you take a look at the OilPressure for instance, you can see that a value is generated every 0.2s (ie 5Hz), while being configured for 10Hz.

**Comment by brentpicasso** [comment]
You can work-around this situation by adding a channel that logs at 50Hz or higher, or changing the Accel/Gyro channel to log at 10Hz or 50Hz.  We will work to get this resolved in an upcoming release.
