### ISSUE TITLE
Add ability to retrieve any channel value from lua

### ISSUE THREAD

**Issue by blalor** [autosportlabs/RaceCapture-Pro_firmware#1048]
I think it'd be useful to retrieve the current value for a channel from a lua script, sort of a genericized version of `getGpsSpeed()` and friends.  For example, retrieving RPM when configured via CAN mapping.

**Comment by brentpicasso** [comment]
getChannel() supports this: https://wiki.autosportlabs.com/RaceCapturePro_Lua_Scripting#getChannel.28_Channel_ID_or_name_.29

**Comment by blalor** [comment]
Derp. I looked and misread that. Thanks!
