### ISSUE TITLE
firmware crashes / watchdogs if addChannel() is called with invalid sample rate

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture-Pro_firmware#107]
Repro:

write this script then power cycle.

rpmId = addChannel("RPM", 30, 0, 0, 9000, "RPM") 

function onTick() end

Observe: repeated crashing / watchdog (until manually bypassed with button)

**Comment by stieg** [comment]
This has been fixed as part of the Lua refactoring.
