### ISSUE TITLE
lua: getAtStartFinish returns bool

### ISSUE THREAD

**Issue by RodADavison** [autosportlabs/RaceCapture-Pro_firmware#1105]
The wiki doc says it returns 1 or 0 but it returns bool.

**Comment by brentpicasso** [comment]
Thanks for reporting, would you be able to fix the docs?

**Comment by RodADavison** [comment]
I don't believe I have write access.

**Comment by brentpicasso** [comment]
Ok.  It has been fixed.

**Comment by RodADavison** [comment]
I am happy to do fixes like this.  Give me access when you have a few minutes.
