### ISSUE TITLE
Auto detect the presence of the telemetry and BT / wifi module and auto-configure accordingly

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture-Pro_firmware#133]

**Comment by stieg** [comment]
We already do this somewhat.  Re-open if there is a more specific issue to address.

**Comment by brentpicasso** [comment]
We need this to detect what peripherials are connected to what UARTs.

**Comment by ryandoherty** [comment]
The longer description is to have RCP auto-detect BT/cellular and enable automatically instead of requiring the user to set it via the app. More plug-n-play.

**Comment by stieg** [comment]
/me nods

Ok.
