### ISSUE TITLE
OBD-II - query PIDs with higher sample rates proportionately more often than PIDs with lower sample rates.

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture-Pro_firmware#134]
for example, RPM PID at 10Hz should be queried 10x more often than a coolant PID being requested at 1Hz

**Comment by stieg** [comment]
@brentpicasso Is this still an issue?  What is current behavior if it is?

**Comment by brentpicasso** [comment]
OBD-II PIDs are queried sequentially regardless of the actual desired
sample rate.  An algorithm to proportionally more frequently query PIDs
with faster sample rates would be beneficial.

E.g.

engineTemp at 1Hz
Tps at 10Hz

right now we query CAN PIDs at equal intervals as fast as possible, and
then separately sample the current values at the desired sample rates.

On Mon, Jan 4, 2016 at 10:23 AM, Andrew Stiegmann <notifications@github.com>
wrote:

> @brentpicasso <https://github.com/brentpicasso> Is this still an issue?
> What is current behavior if it is?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/autosportlabs/RaceCapture-Pro_firmware/issues/134#issuecomment-168758546>
> .
>



-- 
Brent Picasso
*Autosport Labs <http://www.autosportlabs.com>*
*Technology for Race and Street*

**Comment by stieg** [comment]
Seems like this should be part of #172

**Comment by stieg** [comment]
I'm thinking of punting this until we fix #172.  Rationale is that since we need to re-tool a major portion of the OBD-II system with CAN anyways it makes more sense to do it all in a single go instead of retooling it now and then rebuilding it later anyways.  Unless there is a major problem presented by not doing this now I saw we punt.

**Comment by brentpicasso** [comment]
I agree, we can potentially address along side #172

**Comment by brentpicasso** [comment]
Done in 2.11.0
