### ISSUE TITLE
MK2 - DMA for FatFS

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture-Pro_firmware#135]

**Comment by stieg** [comment]
Do we have a spare DMA controller that can handle this on MK2?

**Comment by brentpicasso** [comment]
DMA is already partly implemented for FatFS; it polls with a task yield (or
sleep) between waits. I think it's going to be as good as it gets for MK2.
I vote close this issue for now.

On Mon, Jan 4, 2016 at 10:21 AM, Andrew Stiegmann <notifications@github.com>
wrote:

> Do we have a spare DMA controller that can handle this on MK2?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/autosportlabs/RaceCapture-Pro_firmware/issues/135#issuecomment-168758157>
> .
>



-- 
Brent Picasso
*Autosport Labs <http://www.autosportlabs.com>*
*Technology for Race and Street*

**Comment by stieg** [comment]
I would agree.  Until we see a real need for this I think we can close this
