### ISSUE TITLE
Send Cellular Metadata Peridocially in Telemetry stream 

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture-Pro_firmware#138]
We should be collecting some information about how users are sending data.

**Comment by stieg** [comment]
Should send things like:

* Carrier
* Cellular Strength
* GPS Position
* Modem Info

Will need to move away from the transparent mode in the modem to support this as we need the command interface available to query the cell modem (not available in transparent mode).

**Comment by brentpicasso** [comment]
Not feasible to implement given the way we use transparent mode for cellular. Not implementing.
