### ISSUE TITLE
Support calculating distance channel via wheel speed sensor

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture-Pro_firmware#147]
We should support calculating the distance channel via a wheel speed sensor for things like karting or when users complain about GPS drift/inaccuracy.

Things we'll need:

- Distance channel configuration: select via GPS or a wheel speed sensor
- Setting the wheel diameter
- Picking which analog sensor is wheel speed

**Comment by stieg** [comment]
It is my opinion that this is much more complicated and will yield worse results than the proposal outlined by #178.  Thus closing this as won't fix.
