### ISSUE TITLE
New status codes/info for cellular connection

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture-Pro_firmware#153]
A common problem for cellular telemetry is the customer's SIM card is either:

1) Expired
2) Out of money
3) On the incorrect plan
4) Wrong APN settings

If we can figure out any of those scenarios based on what happens when we try to initialize the cell module and connect to RCL that will help customers immensely in figuring out their issue on their own.

**Comment by stieg** [comment]
Ticket #182 will have enhanced support for this.  While it can't tell you all the above (since the modem doesn't give info that is that specific) it can tell you if the cell network rejected your card.  We can then plumb this into our messages so users can know that there is an issue with the SIM.
