### ISSUE TITLE
Config setting to log speed and distance in metric or 'merican

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture-Pro_firmware#157]
Many (all) users outside of the US use socialist values for their distance and speed units. We'll need a way to set the units in RCP's config.

Units should also change in the channel units value too.

**Comment by zkdzegede** [comment]
This is very important! American living in Japan and my mechanic can't analyze my data in 'merican.  :(

**Comment by stieg** [comment]
Ties in to #357 and #358.  Closing as those tickets explain our approach better.
