### ISSUE TITLE
Come up with safe way to flash data sections of Flash without requiring we allocate a full buffer for the data in RAM first.

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture-Pro_firmware#158]
This is what caused the MK1 issues in the 2.8.* series of firmware.  We simply ran out of RAM and we couldn't allocate the space we needed to work.  With some trickery and sanity checks we could in theory not allocate the RAM needed to do this.  But it needs time to be thought through... not something we have at this moment.  I understand this is probably a doomed task... but I am filing it none the less so that in the best case I can address this issue.

**Comment by stieg** [comment]
Now that MK1 is in legacy mode, this is a won't fix.
