### ISSUE TITLE
Add RC URL to headers in console.

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture-Pro_firmware#161]

**Comment by meikeric** [comment]
I'll start with this one... What exact URL do you want it to point to?

**Comment by brentpicasso** [comment]
Hi, thanks. I'm not even sure what this issue is for we might close it out. Anyone?

**Comment by stieg** [comment]
What @ryandoherty wanted here was to have our URL for our site appear in the interactive serial console.  So when you connect via serial and hit enter twice you will see the welcome screen.  He wants the URL in there.

**Comment by meikeric** [comment]
So... www.autosportlabs.com? www.podium.live?

**Comment by brentpicasso** [comment]
Oh, adding something to the welcome message. So, it would be http://www.autosportlabs.com then.

**Comment by ryandoherty** [comment]
This ticket was created by my account when we moved from Trello to GH, but I didn't create the original task.
