### ISSUE TITLE
Wifi module support

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture-Pro_firmware#165]
support the ESP8266 module on the wireless or Aux port. possibly have an auto-detect mechanism.

**Comment by zkdzegede** [comment]
I'm working on spoofing the BT connection using this chip but having trouble reading the UART commands.  We're you able to get that part up and working? 

I can send and receive from the esp tx/tx to itself and receive messages, but when I try the same with the rcp it cannot even read its own messages. I'm not sure what's going on... Any idea?

**Comment by brentpicasso** [comment]
Hi, also posted on the forums.

For connecting things to the RJ11, make sure you're using RS232 signaling. regular UART signaling won't work (and may damage components that expect just UART / TTL signaling ). 

A good test would be to USB to serial adapter to the serial port and test it with a terminal program.

**Comment by stieg** [comment]
This is currently working (albeit not complete).  Going to close this
