### ISSUE TITLE
Allow the ability to specify a full OBD-II PID request, for custom OEM specific PIDs

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture-Pro_firmware#167]

**Comment by stieg** [comment]
Seems very similar to #172.  Only difference is that #172 would need support to make a request first and the read the response.

**Comment by kosenko-max** [comment]
Any milestone estimations?

**Comment by stieg** [comment]
Closing as a dupe of #172.  We should implement this as part of that patch.
