### ISSUE TITLE
Speed based auto-start/stop logging

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture-Pro_firmware#169]
Rough spec:

- User can enable/disable this feature
- User can configure the speed to start/stop logging
- Some simple cooldown period is needed to prevent flapping. Speed => N for 1s == start. Speed < N for 5s == stop. Behavior is it should start logging 'asap' and be reluctant at stopping to prevent missing data.
- Default for the firmware should be 5mph and enabled. 
- App will have a new section or feature to allow users to configure easily
- Lua start/stop logging can still override this behavior. RCP should log to the system log how SD card logging was enabled and disabled so it can be determined what started and stopped the SD card logging.

**Comment by brentpicasso** [comment]
Also - 

"is engine running" auto logging option.  Could be based on battery voltage, or RPM channel

**Comment by stieg** [comment]
Lets try and sneak this in as part of 2.10

**Comment by brentpicasso** [comment]
agreed. it's time.

**Comment by stieg** [comment]
So for this revision of the feature I am going to do speed based auto start/stop only.  RPM adds complications because I don't know which channel to monitor or which channel is the correct RPM channel to monitor (since there is a chance there could be more than one).

The main question I have now are what our default values should be.  Should this be enabled by default since its a new feature and users are not used to having it?  I can see both sides of the fence here really.  On one hand if they don't have an SD card installed we will try to log to something that doesn't exists and that will turn on the red light and may create user issues.  On the other hand we want things to "just work".  I'm typically of the camp of "make the user enable the feature" so they explicitly know they did it.  Tends to create a bit less confusion that way.  Thoughts?

**Comment by ryandoherty** [comment]
+1 for just speed based for now. Simple and effective.

Defaulting to on for current customers could cause problems, but defaulting to off will make our new customers' experience worse. If we didn't have LuaScript, I'd be 100% behind enabling it by default. 

I'm thinking we have the default of it being on and log when speed is > 5MPH. We'd need some very strong messaging for users. 

Having a red light turn on if there's no SD card is fine, by default users will want to log data so RCP should tell people when it can't. If they don't want SD card logging, they can turn it off.

**Comment by brentpicasso** [comment]
I agree making this simple for now, advise on designing the configuration API with extensibility in mind.

To trigger on other sensors we could maintain a list of other sensor inputs to trigger on and make that configurable by sensor index (0-8 for analog) (0-2 for timer) (0-2 for GPIO) etc. Start and stop thresholds would likely be the same.

**Comment by ryandoherty** [comment]
Also, we need a spec for the API message to configure this so we can get it into 1.7.0 (we may need to delay 2.10.0 to allow us to release a new app)

**Comment by brentpicasso** [comment]
Also, agree on having it on by default as well.

**Comment by jeffmcaffer** [comment]
Random user point of view...  On by default is fine for me.  I get to delete that part of my Lua script.  For trigger speed, I tend to go for something higher (e.g., 20mph).  Less and it triggers just driving around the paddock and to/from the hot pits making lots of little log files to delete.  If I'm heading out on the track 20 is plenty early.  Plus >5mph && > 1s likely is >20mph :-)  For launch/autocross scenarios that may be different.

**Comment by stieg** [comment]
Thanks for the feedback.  Currently it is off by default.  I will change this to on by default.  As for defaults here is what I currently have:

```c
#define DEFAULT_START_SPEED_MPH 25
#define DEFAULT_START_TIME_SEC  5
#define DEFAULT_STOP_SPEED_MPH  3
#define DEFAULT_STOP_TIME_SEC   30
```

This in code translates to the following:

* If you maintain speed >= 25MPH for more than 5 seconds, logging will turn on.
* If you maintain speed <= 3MPH for more than 30 seconds, logging will turn off.

That sounds pretty reasonable to me but am open to suggestions accompanied by reasoning.

**Comment by stieg** [comment]
Changed stop speed and time to the following:

```c
#define DEFAULT_STOP_SPEED_MPH  15
#define DEFAULT_STOP_TIME_SEC   10
```

**Comment by stieg** [comment]
Merged
