### ISSUE TITLE
possibly change log file format to include metadata on comment lines above headers

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture-Pro_firmware#174]
feedback has been that embedding metadata in the column names has been problematic for software. possibly move metadata to a commented out row at the top of the file. perhaps the serialized JSON channel meta format.
# { metadata....}

**Comment by stieg** [comment]
Interesting idea.  To better solve this we need to decide what software we are trying to support first.  And saying "All of it" is not acceptable.  Once we know what we intend to support we can better figure out what needs to change and enact appropriate changes.
