### ISSUE TITLE
text based alert statuses

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture-Pro_firmware#175]
add a text field for the status API that can be set from Lua

id = addAlert(severity, message)
removeAlert(id)
clearAlerts()

Up to 100 characters?

**Comment by stieg** [comment]
I can imagine this getting really annoying really quickly.  Is this a real use case we need to support?

**Comment by brentpicasso** [comment]
This is a place holder to allow RCP to send some kind of up stream alert
notification. But I don't like it b/c RCP shouldn't be aware of any
particular display, adhering to separation of concerns. Still, if a coded
alert condition could be broadcasted that could be useful.


On Sun, Jan 3, 2016 at 10:15 PM, Andrew Stiegmann <notifications@github.com>
wrote:

> I can imagine this getting really annoying really quickly. Is this a real
> use case we need to support?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/autosportlabs/RaceCapture-Pro_firmware/issues/175#issuecomment-168591273>
> .
>



-- 
Brent Picasso
*Autosport Labs <http://www.autosportlabs.com>*
*Technology for Race and Street*

**Comment by stieg** [comment]
IMHO this feature isn't best on RCP itself.  Rather this should be some form of RCL feature that is easily configured using a web UI.  The cost to benefit ratio of implementing this feature in firmware seems too low to be worth it.  Would you agree?  If not, please re-open.
