### ISSUE TITLE
Predicted lap time errors

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture-Pro_firmware#177]
When testing at The Ridge we saw the predicted lap time have huge swings in values when exiting the last turn of the track on to the main straight. It happened 6 times in a row.

The behavior was as we exited the last turn (which is the last of 3 very slow turns), the predicted lap time jumped up by about 1-2 minutes. It would hold that value (+/- a few seconds) until start finish. 

Not sure how to reproduce it, I'll see about getting logs.

**Comment by stieg** [comment]
Without a clearer definition of the issue at hand this is a wild goose chase.  Need some kind of data log showing the inaccuracies.  Re-open is one is provided where a better diagnoses can be achieved.
