### ISSUE TITLE
Fix compiler warning and set strict compilation standards for both MK1 and MK2

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture-Pro_firmware#180]
Seeing this warning in MK2 build

../src/logger/loggerApi.c: In function 'api_setScript':
../src/logger/loggerApi.c:1622:10: warning: variable 'reload_script' set but not used [-Wunused-but-set-variable]

This should never happen.  Need -Wall flag to be set.

**Comment by stieg** [comment]
Strict compilation is enabled in the 2.9 branch for MK2.  With MK1 in a separate branch we can now close this.

**Comment by stieg** [comment]
Port this to 2.8.7
