### ISSUE TITLE
reset distance through lua script. Right now it only resets via a lap or power cycle.

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture-Pro_firmware#183]

**Comment by stieg** [comment]
@ryandoherty Can you help me with a use case for this?  When/why would a person want/need this?

**Comment by stieg** [comment]
@brentpicasso Can you shed any light on this one?  Else I'm going to close it

**Comment by brentpicasso** [comment]
If lap timing is not enabled then distance will increment forever until RCP
is power cycled. A lua command will provide some kind of opportunity to
reset distance outside of lap timing.

On Sun, Jan 3, 2016 at 10:09 PM, Andrew Stiegmann <notifications@github.com>
wrote:

> @brentpicasso <https://github.com/brentpicasso> Can you shed any light on
> this one? Else I'm going to close it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/autosportlabs/RaceCapture-Pro_firmware/issues/183#issuecomment-168590432>
> .
>



-- 
Brent Picasso
*Autosport Labs <http://www.autosportlabs.com>*
*Technology for Race and Street*

**Comment by stieg** [comment]
So who would want to use this and why?  Why not define a track (either stage or circuit).  Use case?

**Comment by stieg** [comment]
Closing because no reasonable use case given.
