### ISSUE TITLE
implement double as number for Lua

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture-Pro_firmware#185]
to fix extended CAN ID issue. (29 bit IDs)

**Comment by stieg** [comment]
@brentpicasso fixed this as part of the bitops fix to LUA.  @brentpicasso Did you test if this resolves the 29 bit CAN value issue?

**Comment by brentpicasso** [comment]
Yes, it does, b/c our problem was with CAN IDs being destroyed by our use
of float. I had tested it back when it was first identified.

On Thu, Jan 14, 2016 at 3:17 PM, Andrew Stiegmann <notifications@github.com>
wrote:

> @brentpicasso <https://github.com/brentpicasso> fixed this as part of the
> bitops fix to LUA. @brentpicasso <https://github.com/brentpicasso> Did
> you test if this resolves the 29 bit CAN value issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/autosportlabs/RaceCapture-Pro_firmware/issues/185#issuecomment-171813433>
> .
>



-- 
Brent Picasso
*Autosport Labs <http://www.autosportlabs.com>*
*Technology for Race and Street*

**Comment by stieg** [comment]
I meant have you verified that the fix actually works.

**Comment by brentpicasso** [comment]
I have verified it in the past via a temporary change to LUA_NUMBER to double,  I have not checked it again since we added bitOp just recently.

**Comment by stieg** [comment]
Ok.  That is probably good enough.  Going to close this for now.
