### ISSUE TITLE
expose OBD-II data to Lua, somehow.

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture-Pro_firmware#186]
RPM can be read by OBD-II, but it's not accessible via Lua.  If a user wants sequential shift lights, there's no way to get at the OBD-II channel data for that.

**Comment by imhoffj** [comment]
This would be awesome. I am currently looking into this same situation and want to use OBD2 for many of the scripting and custom PID - thanks for the software and going to try and set this up and see how far I can go. Thanks for making it open source and really excited!

**Comment by stieg** [comment]
This can probably get fixed as part of the patch to address #172.
