### ISSUE TITLE
Bluetooth initialization problem

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture-Pro_firmware#209]
Bluetooh initializes too fast (race condition before BT module is ready)

**Comment by stieg** [comment]
@ryandoherty Huh... Can you elaborate more on this?

**Comment by brentpicasso** [comment]
I think I opened this, and corresponds to the delay before we try to talk
to the module. We need to wait some amount of time before we can
communicate with module.

The delay is not specified and the module does not output a startup message
AFAIK so we have to blindly wait.

Brent Picasso
Autosport Labs
Technology for Race and Street

**Comment by stieg** [comment]
Ahh that is most certainly a part of this fix (it was already there, but added some pauses when we change the serial baud).

**Comment by stieg** [comment]
Closing because merged
