### ISSUE TITLE
need customer accessible downloads for nightly and released versions of software

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture-Pro_firmware#210]
RIght now we're hand-editing the wiki and hand uploading files to autosportlabs.net.  

We need a customer-browsesable set of pages that will show the things that can be downloaded.

idea: there are some apache modules that provide nice formatting for directory browsing. 

idea URL? http://autosportlabs.com/downloads

**Comment by stieg** [comment]
Customers don't care enough right now.  Hence closing due to lack of interest.

**Comment by kosenko-max** [comment]
I wouldn't say they don't care. I don't know how many of them care about it
same as me...

**Comment by stieg** [comment]
Fair enough... I should rephrase that as "Not enough interest has been shown to warrant the work".  If you want a nightly just ask.  If I get asked enough I imagine I might make the feature :D
