### ISSUE TITLE
floating point overflow in string parsing

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture-Pro_firmware#338]
when parsing a floating point number with a very long fractional value, conversion is incorrect. Need to limit number of decimal places during conversion. 6-10?

**Comment by stieg** [comment]
@ryandoherty Can you elaborate on this more.  What did you expect vs what did you see.  What were you doing to cause this issue?  What version of the firmware did you see this on?  TIA.

**Comment by ryandoherty** [comment]
Hmm, I think this ticket was created when we moved from Trello to GH (I used a script that used my GH credentials). I have no idea what any of this is about :P

**Comment by brentpicasso** [comment]
kill it!

On Mon, Jan 4, 2016 at 8:34 AM, Ryan Doherty <notifications@github.com>
wrote:

> Hmm, I think this ticket was created when we moved from Trello to GH (I
> used a script that used my GH credentials). I have no idea what any of this
> is about :P
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/autosportlabs/RaceCapture-Pro_firmware/issues/338#issuecomment-168726113>
> .
>



-- 
Brent Picasso
*Autosport Labs <http://www.autosportlabs.com>*
*Technology for Race and Street*

**Comment by stieg** [comment]
Closing due to insufficient information on issue.
