### ISSUE TITLE
Change telemetry hostname to telemetry.race-capture.com

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture-Pro_firmware#341]
In order to properly handle telemetry data sent to race-capture.com, the domain name use should be changed to telemetry.race-capture.com

**Comment by brentpicasso** [comment]
What are the thoughts of cut-off period for people running older firmware?

**Comment by brentpicasso** [comment]
Also, will there be a way to tell how many people are hitting the old hostname so we can have a clue of when to cut people off?
