### ISSUE TITLE
Adjust BT name of RCP units to include last 4 digits of serial

### ISSUE THREAD

**Issue by stieg** [autosportlabs/RaceCapture-Pro_firmware#344]
Needed because when multiple RCP units are around and you try to pair, it can be very difficult to tell which unit you are looking for.

**Comment by brentpicasso** [comment]
We have APIs for setting the BT name, not yet exposed in the app.

If this feature is implemented, it's important to ensure this is only set
when restoring factory defaults.

On Thu, Nov 12, 2015 at 6:11 AM, Andrew Stiegmann <notifications@github.com>
wrote:

> Needed because when multiple RCP units are around and you try to pair, it
> can be very difficult to tell which unit you are looking for.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/autosportlabs/RaceCapture-Pro_firmware/issues/344>.
>



-- 
Brent Picasso
*Autosport Labs <http://www.autosportlabs.com>*
*Technology for Race and Street*

**Comment by stieg** [comment]
Agreed.  It would only apply if a factory reset happens.  That is how I will program the patch.

**Comment by stieg** [comment]
Hrmm... interesting issue here.  The BT device name is set when the unit boots.  So if the unit boots and the BT name has been changed, it will be reflected during that boot.  That seems logical but maybe you may disagree @brentpicasso

**Comment by stieg** [comment]
Closing because merged.
