### ISSUE TITLE
Reduce GPS Baud Rate

### ISSUE THREAD

**Issue by stieg** [autosportlabs/RaceCapture-Pro_firmware#351]
GPS baud rate on 2.8.5 and others is quite high.  Something like 921600bps.  I wonder if this is causing instability in communication between the GPS module and the processor.  I have seen these issues in the field and this forum post reminds me of them:

https://www.autosportlabs.org/posting.php?mode=reply&t=4615

I propose we try lowering this rate to see if it helps.

**Comment by brentpicasso** [comment]
The baud rate is set to the mfg recommended speed according to their datasheet. 921600 baud is not an unusual bad rate for transmitting between peripherals on the same board when components are within inches of each other (GPS module and processor).

If there are any errors or timeouts, it is very much likely not related to baud rate. Our initialization code requires a few attempts to synchronize to the stream when using DMA. The other possible issue is likely a defective GPS module, which has been observed in the past.

**Comment by stieg** [comment]
@brentpicasso I see these disconnects on both my units somewhat frequently.  It may not be an unusual rate, but the symptoms I see appear to be ones seen when devices get out of sync with one another.  If its not related to baud, what would you attribute it to?  I suggest we try reducing the baud by 2 or 4 and see if it makes a difference in stability.  Defective GPS systems do happen, but the rate of which I see issues indicates something greater than that.

**Comment by brentpicasso** [comment]
There's no evidence that reducing the baud rate improves anything, and we're using the baud rate currently recommended by the GPS module mfg.  Closing this. re-open if compelling reason to re-investigate it.
