### ISSUE TITLE
Switch accelerometer to SAE standard orientation

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture-Pro_firmware#360]
X should be Forward / aft G's
Y should be lateral G's
Z should be vertical G's

**Comment by stieg** [comment]
The following links clarify:

* https://claraty.jpl.nasa.gov/man/software/development/conventions/coord_frames.php
* https://law.resource.org/pub/us/cfr/ibr/005/sae.j1733.1994.html
* http://www.formula1-dictionary.net/Images/motion_yaw_pitch_roll.jpg
