### ISSUE TITLE
Fix units conversion for currently supported OBD-II channels

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture-Pro_firmware#370]
We have a number of OBD-II channels that are reporting in metric units, but our units are set to imperial.

Until we have full conversion capability in place within the firmware, we should make the OBD-II data report back in the expected units.

Correct the following channels:

EngineTemp. Reports in C, should be F
IAT. Reports in C, should be F
OilTemp. Reports in C, should be F

**Comment by stieg** [comment]
Closing this as it was already fixed by https://github.com/autosportlabs/RaceCapture-Pro_firmware/pull/372
