### ISSUE TITLE
logfile headers min/max have wrong values

### ISSUE THREAD

**Issue by toga94m** [autosportlabs/RaceCapture-Pro_firmware#387]
in firmware master/src/logger/fileWriter.c
                append_file_buffer("|");
                appendFloat(decodeSampleRate(sample->cfg->min), precision);
                append_file_buffer("|");
                appendFloat(decodeSampleRate(sample->cfg->max), precision);
                append_file_buffer("|");
                appendInt(decodeSampleRate(sample->cfg->sampleRate));

MIN and MAX shouldn't use decodeSampleRate()
observed on 2.8.5 for MK1

**Comment by brentpicasso** [comment]
In favor of making this a 2.8.7 release in combination with issue #101

**Comment by stieg** [comment]
Issue merged into 2.8.7 branch.
