### ISSUE TITLE
Lua txCAN timeout parameter has no effect

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture-Pro_firmware#404]
The timeout message is available in the lua function, but has no effect down in the STM32 HAL. 

need a way to enable a timeout, or remove the timeout parameter.

Also - in the HAL layer the CAN_device_tx_msg always returns 1; should return 1 or 0 indicating success.

**Comment by stieg** [comment]
Seems that the timeout portion was skipped in the hal implementation.  I see methods for CAN message status and cancellation in the stm32f4xx_can.h file:

```C
/* CAN Frames Transmission functions ******************************************/
uint8_t CAN_Transmit(CAN_TypeDef* CANx, CanTxMsg* TxMessage);
uint8_t CAN_TransmitStatus(CAN_TypeDef* CANx, uint8_t TransmitMailbox);
void CAN_CancelTransmit(CAN_TypeDef* CANx, uint8_t Mailbox);
```

So probably best to implement the timeout here in HAL.

**Comment by stieg** [comment]
This is a 2.9.0 feature since it changes behavior (albeit for the better).

**Comment by brentpicasso** [comment]
Yeah. the Rx method conveniently uses the FreeRTOS queue for timeout.

Since only Lua uses the txCAN function (so far) - we can implement a cheap
sleep() delay loop up until the timeout if the STM32 CAN transmit function
fails to actually send the message. Wouldn't be terrible.

-Brent

On Wed, Jan 27, 2016 at 2:16 PM, Andrew Stiegmann <notifications@github.com>
wrote:

> This is a 2.9.0 feature since it changes behavior (albeit for the better).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/autosportlabs/RaceCapture-Pro_firmware/issues/404#issuecomment-175889226>
> .
>



-- 
Brent Picasso
*Autosport Labs <http://www.autosportlabs.com>*
*Technology for Race and Street*

**Comment by stieg** [comment]
Patch tested and merged.
