### ISSUE TITLE
Send RCPData to RCL on negotiation.

### ISSUE THREAD

**Issue by stieg** [autosportlabs/RaceCapture-Pro_firmware#409]
Send
* Platform <MK1|MK2|RCT>
* Firmware Version <X.Y.Z>
* Cellular Info
* Whatever else is useful.  @ryandoherty ?

**Comment by stieg** [comment]
Lets bump this to 2.8.8 unless it requires a back end change as well.

**Comment by brentpicasso** [comment]
SGTM

**Comment by stieg** [comment]
Already fixed by commit 6d53fd4.  Closing as "Won't fix"
