### ISSUE TITLE
rename stm32_base to MK2

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture-Pro_firmware#420]
stm32_base should be renamed to match the product name, so it's consistent within the file structure

**Comment by stieg** [comment]
Honestly we should create a `platform` directory and be putting that stuff in there.  This is how Linux does it with architectures.

**Comment by brentpicasso** [comment]
:+1:  whatever is consistent and is easy to understand.

**Comment by stieg** [comment]
Kicking this to 2.9.0.  Better done there since this shouldn't block a bugfix release

**Comment by stieg** [comment]
Too large for review.  Fix was commit 6e00cdf61cc3d62a2d4258283cf7b1b2c803fa68 and children.
