### ISSUE TITLE
Enhance Virtual Channel methods to include getChannel ability

### ISSUE THREAD

**Issue by kosenko-max** [autosportlabs/RaceCapture-Pro_firmware#456]
Currently it's cumbersome to get data from channels - you have to make local variables at the time of update. It would be cleaner code if getChannel would read Virtual Channel data.

**Comment by stieg** [comment]
Hey @kosenko-max, Would you provide an example?  I am afraid I'm not quite following you here.  TIA.

**Comment by kosenko-max** [comment]
IDC calculation requires to remember IPW in one place and come to RPM in
another place. It can be done by storing last IPW in variables, but that
increases code size and makes it inconsistent with other log data access
methods.

**Comment by stieg** [comment]
Got it.  Will look into it.

**Comment by stieg** [comment]
New method now [documented on the wiki](https://autosportlabs.net/RaceCapturePro_Lua_Scripting#getChannel.28_.3CChannel_ID_.7C_Channel_Name.3E_.29  Co).  Closing
