### ISSUE TITLE
Clear virtual channels upon Lua Script Reload

### ISSUE THREAD

**Issue by kosenko-max** [autosportlabs/RaceCapture-Pro_firmware#471]
From time to time change of script would not reset existing virtual channels list, so it hits channel count limit and requires power restart of hardware.

**Comment by stieg** [comment]
Yep.  Virtual Channels are only designed for additions.  I'm assuming you are hitting this because you are testing Lua Scripts?

**Comment by kosenko-max** [comment]
I assume that firmware and app should clean-up table of virtual channels
after script update. Am I right?

**Comment by stieg** [comment]
Not quite.  We expect you not to change the channel name.  hence the name check.  Now if that is broken... Then there is a problem

**Comment by kosenko-max** [comment]
Well, since I don't fit in 30 channels I have to jump between scripts and
power restart hardware every time. I just don't really see a point in
storing old channels if script has updated. I can understand a reason to
store app settings of channels even if they don't exist anymore, but not
channels themselves in a firmware or app channel list.

**Comment by brentpicasso** [comment]
Good engineering practices encourage separation of concerns, and that would suggest that updating the script would not reach into a different part of the system to do something - touching virtual channels, for example. That may end up having an unintended side effect someone else with a different, equally justifiable use case.

Perhaps a lua function to clear existing channels might help, then it can be at the top of every script, if necessary?

**Comment by kosenko-max** [comment]
That would work also, I just can't imagine any scenario where channels must
be persistent after script updates. And since power cycling would clean up
this table anyway, whatever this scenario is - it would not work
consistently anyway.

**Comment by stieg** [comment]
in 2.9.0
