### ISSUE TITLE
If a BT client is already connected,  RCP leaves baud rate at 9600

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture-Pro_firmware#482]
if RCP starts up and BT is already connected it leaves the default baud rate at 9600 (the last baud rate it attempted), and then the tablet never can communicate, b/c wrong baud rate.

Under this condition it should reset it to the default programmed baud rate. 

BT: Trying Baudrate: 115200
BT: Trying Baudrate: 57600                                                                                           
BT: Trying Baudrate: 9600                                                                                            
BT: Could not detect device using known baud rates.                                                                  
BT: Failed to communicate with device.                                                                               
BT: Failed to provision module. A client may already be connected.

**Comment by stieg** [comment]
Fix merged for 2.9.0 release
