### ISSUE TITLE
Evaluate Heap Usage and Reduce as Much as is Reasonably Possible.

### ISSUE THREAD

**Issue by stieg** [autosportlabs/RaceCapture-Pro_firmware#500]
It has become quite clear that we are using more RAM that is generally sane/reasonable.  To avoid this and restore stability in the system we need to focus on using less RAM where possible.  This ticket tracks doing a review of the code, identifying large sinks of RAM, and trimming/eliminating them as needed.  Places of note:
- Message Rx Buffers for incoming data
- Serial buffers
- Lua Library usage
- Memory buffers allocated for API commands

This ticket only tracks searching and identifying these problems.  Lets then file a ticket for each one and address accordingly.

**Comment by brentpicasso** [comment]
Also should analyze CCM usage vs heap; we may be leaving much memory on the table in CCM where some malloc'd structures can be moved to.

**Comment by stieg** [comment]
Very possible.  I can tweak some of our objects to make use of statically allocated buffers if necessary, its just not as ideal.
