### ISSUE TITLE
RCT: periodic watchdog issue

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture-Pro_firmware#501]
Periodically RCT will watchdog while simply transmitting data.  search and destroy

**Comment by stieg** [comment]
No bueno.  Anything specific actions being taken or is it apparently random?

**Comment by brentpicasso** [comment]
Unknown except that it happens.  A breakpoint will be the first step.

Brent Picasso
Autosport Labs
Technology for Race and Street

**Comment by stieg** [comment]
Can't reproduce this.  Closing.
