### ISSUE TITLE
RaceCapture: reset control for wifi module

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture-Pro_firmware#507]
RCT will have control of the reset line for the wifi module. It is wired on PA5. 

To reset, pull PA5 to active low. for normal operation, set to active high.

Reset should be activated upon system power up. If  wifi module becomes unresponsive, it should re-initialize, involving reset.

**Comment by stieg** [comment]
Issue #583 covers the whole bit better.  Lets use that tracker instead of this one.
