### ISSUE TITLE
Remove per channel sample rate in favor of global log rate

### ISSUE THREAD

**Issue by kosenko-max** [autosportlabs/RaceCapture-Pro_firmware#547]
Few things could significantly improve log results if they work together:
1. Change channel filters to simple antialiasing + Kalman filtering with user settings instead of exponential IIR. Filter settings can define how quickly data would change - this allows increase accuracy of data with slower response instead of losing data by decreased sample rate.
2. Omit repetitive log values - together with filtering it would remove most of the noise from the logs and save space on slow moving data
3. Collect data from different sources as fast as possible in a separate threads - ADC, CAN, Serial - those should read data non-stop and most of the time those threads will be sitting waiting for the data, so no real performance impact. Any calculations or data management should be done on a separate threads to avoid data accuracy reduction. Higher frequency of data collection with proper data filtering and approximation always brings better accuracy. Anti-aliasing requires as high frequency as possible.
4. **Use single global setting for logging rate**. That should be used to globally increase accuracy of data while decreasing number of samples in the log.

Take for example fuel pressure sensor - good sensors filter output signal to 500-1000hz, but it assumes that ECU will do further filtering of data based on the specific need of calculations. And fuel pressure at the rail is significantly influenced by injectors pressure noise. If frequency of data collection is low you are reading signal at different phases of the signal and resulted output easily looks like swinging up-down 50%, while in reality it could be standing still and deviating just 2-3%. So log would not only not show real value, but it's also makes it impossible to restore real value from low sampling rate. Applying low pass filter of any kind only makes situation worse, because low and high frequencies already blended together.

**Comment by stieg** [comment]
Wow... this is a lot of work summarized in a single ticket.  I like the idea of a single maximum data sample rate in the system as frankly that makes a lot of sense.  I don't know if I agree that Kalman filters + anti aliasing are easy.  If they were then we probably would have done them already.  Most of our sampling is actually already done by separate threads (a few aren't and this needs to change).  In all this is a very idealistic ticket to solve given resources available.  But the thinking is fairly rational so we should keep it open as an ideal state.  Contributions would be most welcome here to help out, but given current resource limitations this probably won't get done in the near future.
