### ISSUE TITLE
RCT: powering up RCP via power source causes firmware to hang

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture-Pro_firmware#568]
Firmware will hang if powering up RCT via usb power source (no data connection).

STR: plug RCT into a usb battery and observe firmware hang

**Comment by stieg** [comment]
This seems to have been fixed as I am able to run both RCT and MK2 from my power source without seeing a crash.  Not exactly sure what cured it but it may have been related to the IRQ fix if I had to guess.  @brentpicasso can you verify on your end when you have a chance?  But I'm going to close this unless you see the error on your end.
