### ISSUE TITLE
Improve MK2 SDCard Lib to not busy wait

### ISSUE THREAD

**Issue by stieg** [autosportlabs/RaceCapture-Pro_firmware#573]
The SD card library at platform/mk2/hal/fat_sd_stm32/fatfs/lo_level_ub/stm32_ub_sdcard.c is a bit naive and does things it shouldn't do like busy wait for status interrupts to come in.  This causes a bit of hell on our system when a user turns on SDcard logging.  We should not be doing this.  Instead we should either be using DMA or should be using an interrupt driven library to do this.  The taker of this beast should fix that lib to be smarter and use interrupts or even DMA if they are feeling saucy.

**Comment by brentpicasso** [comment]
The library actually does use DMA - it does it in a way that it still waits for the DMA transfer to complete, however, to keep the context in place.
