### ISSUE TITLE
RCT: Bootloader "ActionSwitch" port mapping

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture-Pro_firmware#596]
The "Action Switch" for RCT is on PC15 on the F303; behaviour should mimic RCP - when switch activated it is pulled to ground.

PC15 should be enabled with an internal pull-up.

**Comment by Jeff-Ciesielski** [comment]
This is closed out as of: https://github.com/autosportlabs/ASL_F4_bootloader/commit/7601478d2ad0490fdd87cd12977743173f671e24
