### ISSUE TITLE
Switch from deprecated AT commands to _CUR variants

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture-Pro_firmware#612]
need to switch to the _CUR variants of configuration AT commands for ESP8266.
https://espressif.com/en/file/721/download?token=5D4jCASk
e.g.

AT+CWMODE
AT+CWJAP
AT+CWSAP
AT+CWDHCP

**Comment by stieg** [comment]
Merged

**Comment by stieg** [comment]
Merged
