### ISSUE TITLE
Support Measuring Lower RPM Rates

### ISSUE THREAD

**Issue by stieg** [autosportlabs/RaceCapture-Pro_firmware#639]
We need to be able to measure lower RPM rates with accuracy.  As documented by autosportlabs/RaceCapture-Pro_firmware#516 the lowest single pulse RPM rate we support as of 2.9.0 is currently 90 RPM.  I propose we adjust our prescalars so that the following is true:

Speed | Lowest Supported Hz Measurement
-------- | -----------------------------------------------
Fast | 10 Hz
Medium | 1 Hz
Slow | 0.1 Hz

This should give us the breadth of measurement we need to be extremely flexible while only minimally sacrificing precision (which is frankly quite high as is).  This would change the tables to something like this:

Speed | Prescalar | Lowest (Hz) | Lowest (RPM) | Highest (Hz) | Highest (RPM)
-------- | ------------ | --------------- | ----------------- | ---------------- | -------------------------
Fast | 110 |10 | 600 | 655350 | 39321056
Medium | 1101 | 1 | 60 | 65535 | 3932105
Slow | 11010 | 0.1 | 6 | 6553 | 393210

This looks very reasonable since folks can use the fast speed to retain the same high precision RPM measurements they have today.  They can use the medium for slower engines or faster shafts.  And the slow speed is available for anyone measuring something that turns at some very low rate for some unknown reason.

**Comment by brentpicasso** [comment]
looks like a good compromise.

**Comment by stieg** [comment]
I messed up my original prescalar calculations apparently.  I have since updated them.  But the lowest measurable Hz remains unchanged.

**Comment by stieg** [comment]
Merged
