### ISSUE TITLE
Lua Scripting Repository Contrib

### ISSUE THREAD

**Issue by psallandre** [autosportlabs/RaceCapture-Pro_firmware#657]
What about creating a repository RaceCapturePro_LuaContrib?
It would be great to have a central repository with some Lua scripts.
Then everyone could contribute with car platform specific scripts or some clever scripts!
Hopefully it would evolve in high value knowledge...

**Comment by stieg** [comment]
Not a bad idea honestly.  If you start one with an open license we can always clone the repo into our care and maintain it as well (part of why Git is wonderful).  I have several scripts on my side that would be great to make public.

**Comment by psallandre** [comment]
Good you like the idea :)
I don't have mature enough script but when I do, I'll make them public for sure!
In the interval, why not you create this repository and push those great scripts :)? It would make it alive and probably attracts more contributors.

**Comment by brentpicasso** [comment]
Great idea!

We created a repo here, feel free to submit Pull requests:

https://github.com/autosportlabs/RaceCapture_Lua_Scripts

Of course, we have our regular, more curated list of Lua scripting examples
here too:

https://autosportlabs.net/RaceCapturePro_Lua_Scripting_Examples

-Brent

On Mon, Jun 6, 2016 at 1:28 PM, psallandre <notifications@github.com> wrote:

> Good you like the idea :)
> I don't have mature enough script but when I do, I'll make them public for
> sure!
> In the interval, why not you create this repository and push those great
> scripts :)? It would make it alive and probably attracts more contributors.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/autosportlabs/RaceCapture-Pro_firmware/issues/657#issuecomment-224077772>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADHbzfBGyc_26Ks-vKICZz0PqnXgkNOvks5qJILTgaJpZM4IvRYh>
> .
>



-- 
Brent Picasso
*Autosport Labs <http://www.autosportlabs.com>*
*Technology for Race and Street*

**Comment by psallandre** [comment]
Cool!
I'll try and feed it as soon as I can
