### ISSUE TITLE
Diagnose and Fix "SEND FAIL" Issue

### ISSUE THREAD

**Issue by stieg** [autosportlabs/RaceCapture-Pro_firmware#660]
After running for about 3 minutes or so I start to notice the following error messages appearing in our log files:
```
[at] Unhandled msg received: SEND FAIL
```
Turning on serial debug we see the following:
```
[serial (WiFi)] TX: AT+CIPSEND=0,104(\r)(\n)
[serial (WiFi)] RX: (\r)(\n)
[serial (WiFi)] RX: OK(\r)(\n)
[serial (WiFi)] TX: {"beacon":{"name":"RCT","port":7223,"serial":"FFFF738CFFFFFFFFB946CE31","ip":["0.0.0.0","192.168.4.1"]}}
[serial (WiFi)] RX: > (\r)(\n)
[serial (WiFi)] RX: Recv 104 bytes(\r)(\n)
[serial (WiFi)] RX: (\r)(\n)
[serial (WiFi)] RX: SEND OK(\r)(\n)
[serial (WiFi)] RX: SEND FAIL(\r)(\n)[at] Unhandled msg received: SEND FAIL
```
Error is coming from our beacon but nothing is wrong with the beacon itself AFAICT.  Issue may be related to the esp8266 device.  Need to understand the meaning of this message and see how we can make it disappear.  This message shouldn't exist to begin with since this beacon is using UDP with a link-local broadcast address.  So really there is nothing to fail sending wise.  But what is more strange is that the device first sends `SEND OK` followed immediately by `SEND FAIL`.

**Comment by brentpicasso** [comment]
Does it get stuck in 'send fail' or does it occur sporadically?

This might help:
http://bbs.espressif.com/viewtopic.php?t=1256

Also, does this also occur with TCP packets?

-Brent



On Mon, Jun 6, 2016 at 8:49 PM, Andrew Stiegmann <notifications@github.com>
wrote:

> After running for about 3 minutes or so I start to notice the following
> error messages appearing in our log files:
>
> [at] Unhandled msg received: SEND FAIL
>
> Turning on serial debug we see the following:
>
> [serial (WiFi)] TX: AT+CIPSEND=0,104(\r)(\n)
> [serial (WiFi)] RX: (\r)(\n)
> [serial (WiFi)] RX: OK(\r)(\n)
> [serial (WiFi)] TX: {"beacon":{"name":"RCT","port":7223,"serial":"FFFF738CFFFFFFFFB946CE31","ip":["0.0.0.0","192.168.4.1"]}}
> [serial (WiFi)] RX: > (\r)(\n)
> [serial (WiFi)] RX: Recv 104 bytes(\r)(\n)
> [serial (WiFi)] RX: (\r)(\n)
> [serial (WiFi)] RX: SEND OK(\r)(\n)
> [serial (WiFi)] RX: SEND FAIL(\r)(\n)[at] Unhandled msg received: SEND FAIL
>
> Error is coming from our beacon but nothing is wrong with the beacon
> itself AFAICT. Issue may be related to the esp8266 device. Need to
> understand the meaning of this message and see how we can make it
> disappear. This message shouldn't exist to begin with since this beacon is
> using UDP with a link-local broadcast address. So really there is nothing
> to fail sending wise. But what is more strange is that the device first
> sends SEND OK followed immediately by SEND FAIL.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/autosportlabs/RaceCapture-Pro_firmware/issues/660>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADHbzXVdnOWvcr2FSoBF0xKKHcG7F_Enks5qJOpngaJpZM4IviBL>
> .
>



-- 
Brent Picasso
*Autosport Labs <http://www.autosportlabs.com>*
*Technology for Race and Street*

**Comment by stieg** [comment]
I saw that thread and it didn't help me much.  This is a UDP beacon, no TCP
involved.  Need to diagnose issue more before I can make any further
statements


On Mon, Jun 6, 2016 at 11:53 PM, Brent Picasso <notifications@github.com>
wrote:

> Does it get stuck in 'send fail' or does it occur sporadically?
>
> This might help:
> http://bbs.espressif.com/viewtopic.php?t=1256
>
> Also, does this also occur with TCP packets?
>
> -Brent
>
>
>
> On Mon, Jun 6, 2016 at 8:49 PM, Andrew Stiegmann <notifications@github.com
> >
> wrote:
>
> > After running for about 3 minutes or so I start to notice the following
> > error messages appearing in our log files:
> >
> > [at] Unhandled msg received: SEND FAIL
> >
> > Turning on serial debug we see the following:
> >
> > [serial (WiFi)] TX: AT+CIPSEND=0,104(\r)(\n)
> > [serial (WiFi)] RX: (\r)(\n)
> > [serial (WiFi)] RX: OK(\r)(\n)
> > [serial (WiFi)] TX:
> {"beacon":{"name":"RCT","port":7223,"serial":"FFFF738CFFFFFFFFB946CE31","ip":["0.0.0.0","192.168.4.1"]}}
> > [serial (WiFi)] RX: > (\r)(\n)
> > [serial (WiFi)] RX: Recv 104 bytes(\r)(\n)
> > [serial (WiFi)] RX: (\r)(\n)
> > [serial (WiFi)] RX: SEND OK(\r)(\n)
> > [serial (WiFi)] RX: SEND FAIL(\r)(\n)[at] Unhandled msg received: SEND
> FAIL
> >
> > Error is coming from our beacon but nothing is wrong with the beacon
> > itself AFAICT. Issue may be related to the esp8266 device. Need to
> > understand the meaning of this message and see how we can make it
> > disappear. This message shouldn't exist to begin with since this beacon
> is
> > using UDP with a link-local broadcast address. So really there is nothing
> > to fail sending wise. But what is more strange is that the device first
> > sends SEND OK followed immediately by SEND FAIL.
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/autosportlabs/RaceCapture-Pro_firmware/issues/660>,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/ADHbzXVdnOWvcr2FSoBF0xKKHcG7F_Enks5qJOpngaJpZM4IviBL
> >
> > .
> >
>
>
>
> --
> Brent Picasso
> *Autosport Labs <http://www.autosportlabs.com>*
> *Technology for Race and Street*
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/autosportlabs/RaceCapture-Pro_firmware/issues/660#issuecomment-224176027>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAIozztEKPDq3UIkbAoqOfs4B0F0r0Xlks5qJPlFgaJpZM4IviBL>
> .
>



-- 
Autosport Labs
*Open Source Motor Sports*

**Comment by stieg** [comment]
Ahh... I think this may be a regression caused by one of my changes.  Namely just came across the dandy of a Note in the expressif manual: `Note: [<UDP mode>] can only be used when [<UDP local port>] is set`.  I removed those parameters recently, and saw no errors so assumed it was fine.  I would bet that its the cause.

**Comment by brentpicasso** [comment]
\o/ ? :)

On Tue, Jun 7, 2016 at 9:43 AM, Andrew Stiegmann <notifications@github.com>
wrote:

> Ahh... I think this may be a regression caused by one of my changes.
> Namely just came across the dandy of a Note in the expressif manual: Note:
> [<UDP mode>] can only be used when [<UDP local port>] is set. I removed
> those parameters recently, and saw no errors so assumed it was fine. I
> would bet that its the cause.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/autosportlabs/RaceCapture-Pro_firmware/issues/660#issuecomment-224340604>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADHbzUJb3XS-DolHzgWumKVEu576Wkfrks5qJZ-VgaJpZM4IviBL>
> .
>



-- 
Brent Picasso
*Autosport Labs <http://www.autosportlabs.com>*
*Technology for Race and Street*

**Comment by stieg** [comment]
> \o/ ? :)

Heh... we will see.  I'm just glad to have someplace to start here :P
