### ISSUE TITLE
Verify RC created wifi network has correct settings to tell phones to use cellular connection for data

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture-Pro_firmware#677]
Because the RC wifi network does not have actual internet connectivity, the wifi settings need to be setup so phones/tablets understand there is no internet access. Possibly gateway settings?

**Comment by stieg** [comment]
What are these correct settings exactly?  Do you know off-hand?  If not I guess first item is to figure out what they are.
