### ISSUE TITLE
explore use  of AT+CIPSENDBUF to improve WiFi performance

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture-Pro_firmware#678]
The AT+CIPSENDBUF is an AT command that allows queuing data into the ESP8266's send buffer, vs AT+CIPSEND, which seems to wait until a packet is fully broadcasted.

**Comment by stieg** [comment]
Removing this from 2.10.0 since measurement has shown that the benefit of this work is not really apparent in local connections.

**Comment by brentpicasso** [comment]
Not implementing. Closing.
