### ISSUE TITLE
Script fails to load on 2.10.0

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture-Pro_firmware#697]
This GoPro script fails to load on 2.10.0
https://wiki.autosportlabs.com/RaceCapturePro2_GoProWiFi

[lua] Loading script. Length: 2647
[lua] Successfully loaded script.
[lua] Script error: [string "--Specify your GoPro wifi password here..."]:30.0: BUG. Please inform AutosportLabs
[lua] Script error: [string "--Specify your GoPro wifi password here..."]:30.0: BUG. Please inform AutosportLabs
[lua] Script error: [string "--Specify your GoPro wifi password here..."]:30.0: BUG. Please inform AutosportLabs
[lua] Failure: Runtime Error

This script works as expected on 2.9.2

**Comment by stieg** [comment]
Huh... its choking on the first line of the script yet the parser is printing it out as line 30.  That is odd.

**Comment by brentpicasso** [comment]
seems that even a script like this fails:

function onTick()
println("foo")
end

**Comment by stieg** [comment]
Heh... the bug seems to be somewhere in the `println` method
