### ISSUE TITLE
Add "Session Statistics" to Firmware for Quick Stats Access

### ISSUE THREAD

**Issue by stieg** [autosportlabs/RaceCapture-Pro_firmware#747]
Access to statistics about a session would be a wonderful thing to have available immediately as you come off track.  Things of importance are
- Max RPM
- Max Speed
- Standard deviation of 80% of laps (Gets you consistency).
- Info on top 3 lap times including:
  *\* Lap times
  *\* Top Speeds
  *\* Top RPMs
  *\* Temps

I'm sure there is more here but the idea with this is when it comes to test/tune days you really want this info as soon as you get off-track so you can adjust and go right back out and test.  Having this makes things nice and easy to handle.

**Comment by brentpicasso** [comment]
Not implementing in firmware, this should be an app feature.
