### ISSUE TITLE
When socket disconnects, should stop streaming

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture-Pro_firmware#766]
If streaming is enabled on a socket, and then the socket disconnects, a series of event overflow errors shows up in logs:

[wifi] Event overflow: Sample CB
[wifi] Event overflow: Sample CB
[wifi] Event overflow: Sample CB
[w

**Comment by stieg** [comment]
Yeah... this is the disconnect support that I need to add.  This is trickier since we have never supported anything like this in the past.  But the times they are a changing I suppose... Time to have the serial device grow up.

**Comment by stieg** [comment]
With the merging of #777 this issue is now resolved.
