### ISSUE TITLE
Cannot reconnect via Wifi 

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture-Pro_firmware#795]
observed on RCT, may appear on MK2.

STR:

Connect via WiFi (e.g. android)
Close app
restart app
observe not connecting

power cycle device
observe successful re-connect

**Comment by stieg** [comment]
Wonderful.  Top of tree 2.10.0?  Or something older?

**Comment by stieg** [comment]
Hrmm... wasn't able to reproduce this as described, but did notice that if I execute a `sysReset` call the WiFi does not come back up.  Powercycling the device does indeed fix that.

@brentpicasso Can you confirm if any of your actions would have led to some form of a soft reset of the device.

**Comment by brentpicasso** [comment]
Correct, top of tree.  Very easy to repro

**Comment by brentpicasso** [comment]
Saw the rest of your comments. 

I flashed a non-debug build and used the wifi settings as provided by default.

**Comment by stieg** [comment]
This appears fixed with most recent changed.  Closing.
