### ISSUE TITLE
Set DHCP Client ID to Something Identifiable 

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture-Pro_firmware#798]
STR:

configure as client. e.g. tether to your phone.
Enable phone's hotspot. 
Observe the following:

![image](https://cloud.githubusercontent.com/assets/3267533/17577979/b586a97c-5f38-11e6-83c8-91953d4132b2.png)

**Comment by stieg** [comment]
I do not believe that is the Wifi network name.  Rather what you are seeing is the DHCP client id.  This is an optional parameter used in DHCP to provide some human readable identity to a given device.  In the absence of such an id you usually use just the MAC address of the device.  Here is a little bit more about that name: https://github.com/esp8266/Arduino/issues/768.  Regardless this is not something that is likely to change for 2.10.0.
