### ISSUE TITLE
Lap timing / predictive timing stops working

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture-Pro_firmware#809]
Saw evidence of lap timing stopping completely on this event, despite GPS having a strong signal; GPS position and speed were also updating. (assuming distance as well, but would need to check the raw logs).

https://podium.live/events/chumpcar-the-24-hour-classic-1/device/307-not-banned-yet

Pattern of behavior: Lap timing / Predictive timing works after a power cycle (e.g. pit stop), then some time afterwards lap timing and predictive timing stops completely.

We have the configuration file for the RCP; it has a somewhat complex Lua script aside from the usual analog and digital sensor configurations. 

Thoughts on reproducing:
Create a simulator that can pump raw data right into the GPS tx/rx port, getting as close to real-world emulation as possible.  

Other, less real-world ideas on simulation:
- Get a log from this session and run those through our standard unit tests
- Create a fake GPS HAL device than can receive data updates from an external source (aux serial port, etc)

**Comment by stieg** [comment]
Demoting from 2.10.0 release requirements since this is a bug fix and is thus a candidate for 2.10.1.  WIll try to reproduce before 2.10.0 release.

**Comment by stieg** [comment]
Dropping milestone since not a blocker for 2.10.1

**Comment by brentpicasso** [comment]
This is likely a false alarm due to the task smash and processor reset bus fixed recently in 2.13.5, causing a delay when the predictive timer is running again (after a lap is completed). 

Closing for now, will re-open if necessary.
