### ISSUE TITLE
Optimize Stack Usage; Minimize Stacks

### ISSUE THREAD

**Issue by stieg** [autosportlabs/RaceCapture-Pro_firmware#810]
On RCT I recently learned that if I reduce the USB task stack size too much it will cause a hardfault.  The likely culprit is stack smashing (although it could be something else).  To help eliminate these issues we can implement some stack size checks using `-fstack-usage` and `-Wstack-usage`.

This task track implementing some sane versions of these checks and then reducing stack sizes where possible.

**Comment by stieg** [comment]
We should also reduce the USB task stack size where possible.  Currently it sits at 320 words.

**Comment by brentpicasso** [comment]
Closing, stack sizes seem acceptable for currently supported products.
