### ISSUE TITLE
Track config for devices with no track db have autodetect set to 1

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture-Pro_firmware#814]
RaceCapture with firmware 2.10.0 reports back that autodetect is on:

`{"trackCfg":{"rad":0.0001,"autoDetect":1,"track":{"id":0,"type":0,"sf":[0.0,0.0],"sec":[[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0]]}}}`

It should probably be off since it has no track db.

**Comment by brentpicasso** [comment]
So, the auto detect flag should still be there even if there is no track
db. This is the indicator that the app should select the track
automatically.

**Comment by ryandoherty** [comment]
The bug is that autodetect is set to 1, not that the key exists.

**Comment by stieg** [comment]
Correct.  Need to adjust the default so that if the number of DB entries available is 0, then the auto-detect value is 0.

**Comment by stieg** [comment]
Merged
