### ISSUE TITLE
RCT should not report Bluetooth and Logger status

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture-Pro_firmware#821]
Since RCT does not have these devices, status on these shouldn't be reported.

**Comment by stieg** [comment]
So if I don't report these will the app crash or just assume them to be `null`?

**Comment by ryandoherty** [comment]
The app uses the status dict from the getStatus response to determine which menu items and values to render, so we're good.

**Comment by stieg** [comment]
:+1:
