### ISSUE TITLE
Add lua script function for getting logging status

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture-Pro_firmware#849]
Sometimes in Lua script a user may want to know if their logger is logging so they can then control a GPIO or add some custom behavior. A function like `getLogging()` that returns true/false would be handy.

**Comment by stieg** [comment]
Seems that we have this method already.  It is the `isLogging` method.  I have added documentation about it here: https://wiki.autosportlabs.com/RaceCapturePro_Lua_Scripting#isLogging.28.29.  Closing
