### ISSUE TITLE
Battery voltage showing 0.0 in 2.10.0-RC3 or 2.10.0

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture-Pro_firmware#868]
2.10.0 release does not show battery voltage.  When falling back to RC2, battery voltage does show in telemetry stream.

STR: 
Have 2.10.0_RC2 firmware programmed. observe battery voltage channel working correctly.
flash 2.10.0-RC3 or 2.10.0 official. 
Note battery voltage channel no longer working.

**Comment by stieg** [comment]
Fun.  MK2 or RCT or both?

**Comment by brentpicasso** [comment]
Only observed on RCT; RCP with 2.10.0 shows battery voltage correctly.

**Comment by stieg** [comment]
Regression is caused by either commit 7f8d5fda2 or commit ef72d3981d (not sure which since the latter leads to a panic).  Either way this is strange behavior since neither of the commits muddle with any of the DMA bits or the ADC settings.  Something is going where it shouldn't
