### ISSUE TITLE
Use "null" instead of "0" for some data.

### ISSUE THREAD

**Issue by mumchristmas** [autosportlabs/RaceCapture-Pro_firmware#875]
Some data has special meaning with 0. For example——utc = 0 means "0:00:00, January 1, 1970", gpsdop = 0 means "top accrue position with zero interval".

The firmware now will write zero when the data source is missing(e.g. I parked my car underground). It makes more outlier rejection work to do when we play with the data.

**Comment by stieg** [comment]
Valid point.  However using the phrase "NULL" would break many existing parsers who can't parse strings and expect digits.  Perhaps it would be wiser just to include absolutely nothing to indicate the absence of a measurement.

There would be non trivial changes for this to work internally... namely we would probably need to bump the API version for this new behavior.
