### ISSUE TITLE
GetHighestSampleRate does not check new Custom Can mapped channels

### ISSUE THREAD

**Issue by jlwall** [autosportlabs/RaceCapture-Pro_firmware#927]
When running a log config with only CAN mapped channels, 

> unsigned int getHighestSampleRate(LoggerConfig *config)

Does not take into account anything on the CAN Mapping. The log defaults to 1 seconds.
This should be an easy fix

**Comment by brentpicasso** [comment]
thanks for finding this. Definitely should go into 2.11.1.

**Comment by brentpicasso** [comment]
in the course of fixing this, also discovered that we don't check for highest OBDII sample rate.
