### ISSUE TITLE
Warn when the lua "onTick" call take too much time and delay the next call.

### ISSUE THREAD

**Issue by kokarez** [autosportlabs/RaceCapture-Pro_firmware#988]
Hi, I'm an new user here.

Without this information, it's quite complicated to know if we will really get the onTick frequency that we desire. When we are coding the script it will be nice to warn us about that.

https://github.com/autosportlabs/RaceCapture-
Pro_firmware/blob/0bc2a84ec13a920a3db31df10b60be98c9371f33/src/lua/luaTask.c#L289

```c
portTickType curr_tick = xTaskGetTickCount();
if (curr_tick < wake_tick) {
  /* If signal is given, restart loop, else normal op */
    if (xSemaphoreTake(state.lua_signal, wake_tick - curr_tick))
      continue;
} else {
  pr_error(_LOG_PFX "LUA onTick call took longer than the allocated time.\r\n");
}
```

**Comment by brentpicasso** [comment]
Thanks for the feedback.  we have this covered in https://github.com/autosportlabs/RaceCapture-Pro_firmware/issues/627, which should provide statistics for lua scripting.
